// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-9qZfvAaukL1nDohB_V3Y-3MKDr3Ywxw',
    appId: '1:250597913075:web:1a8885dc11a3872823a286',
    messagingSenderId: '250597913075',
    projectId: 'keyloggerbase-b2cea',
    authDomain: 'keyloggerbase-b2cea.firebaseapp.com',
    databaseURL: 'https://keyloggerbase-b2cea-default-rtdb.firebaseio.com',
    storageBucket: 'keyloggerbase-b2cea.firebasestorage.app',
    measurementId: 'G-7TBP9YEBR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFWWkcaH5oVREVKKm6-GYW1BDoqrQzGoA',
    appId: '1:250597913075:android:a28855329808a68723a286',
    messagingSenderId: '250597913075',
    projectId: 'keyloggerbase-b2cea',
    databaseURL: 'https://keyloggerbase-b2cea-default-rtdb.firebaseio.com',
    storageBucket: 'keyloggerbase-b2cea.firebasestorage.app',
  );

}